name: Delete AWS Resources
on:
  schedule:
    - cron: '0 */1 * * *' # Trigger every hour

jobs:
  delete_resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete AWS Resources
        run: |
          # Navigate to your Terraform project directory
          cd terraform/

          # Initialize Terraform
          terraform init

          # Apply Terraform destroy command with auto-approval
          terraform destroy -auto-approve
