version: '3.7'
services:

  tf:
    image: terraform-poc:latest
    command: /bin/bash -c "sleep 4800"
    volumes:
      - .:/infra
      - /home/codespace/.aws/credentials:/root/.aws/credentials
    working_dir: /infra







