- name: Install Nginx, Python, and Go
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Python and Go
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - golang

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- name: Start Mock API Server
  hosts: webserver
  become: yes
  tasks:
    - name: Copy Mock API Server script
      copy:
        src: mock_api.py
        dest: /opt/mock_api.py

    - name: Start Mock API Server
      command:
        cmd: python3 /opt/mock_api.py
      async: 1
      poll: 0

# - name: Start Python Backend Server
#   hosts: webserver
#   become: yes
#   tasks:
#     - name: Copy Python Backend Server script
#       copy:
#         src: python_backend.py
#         dest: /opt/python_backend.py

#     - name: Start Python Backend Server
#       command:
#         cmd: python3 /opt/python_backend.py
#       async: 1
#       poll: 0

- name: Start Go Backend Server
  hosts: webserver
  become: yes
  tasks:
    - name: Copy Go Backend Server binary
      copy:
        src: go_backend
        dest: /opt/go_backend

    - name: Start Go Backend Server
      command:
        cmd: /opt/go_backend
      async: 1
      poll: 0
