name: Build and Deploy Docker Images
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker images
        run: |
          make build-dev

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1   

      - name: Tag and push Docker images
        env:
          ECR_ACCOUNT: ${{ secrets.ECR_ACCOUNT }}
        run: |
          docker tag everyshilling_app-auth:latest $ECR_ACCOUNT/twala:app-auth
          docker tag everyshilling_app-db:latest $ECR_ACCOUNT/twala:app-db
          docker tag everyshilling_app-otp:latest $ECR_ACCOUNT/twala:app-otp
          docker push $ECR_ACCOUNT/twala:app-auth
          docker push $ECR_ACCOUNT/twala:app-db
          docker push $ECR_ACCOUNT/twala:app-otp


# everyshilling is the stack name
      - name: Deploy Docker stack
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > ~/.aws/credentials
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
          aws ecr get-login-password --region us-east-1 | docker secret create ecr-login -
          docker stack deploy -c dockerswarm-compose.yml everyshilling
